services:
  web:
    build: ./django-aws-backend
    container_name: django_web
    # command: gunicorn -b 0.0.0.0:8000 django_aws.wsgi:application
    volumes:
      - ./django-aws-backend/:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    env_file:
      - ./django-aws-backend/.env

#   db:
#     image: postgres:14
#     container_name: postgres_db
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: django_aws
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: